### ISSUE TITLE
Recursively watch newly created directories

### ISSUE THREAD

**Issue by mikemahony** [tywkeene/go-fsevents#1]
Hi!  Do you plan to support recursive watching of directories that are added after the root watch has started?  And then, conversely, removing watchers when directories are deleted?  Thanks!

**Comment by tywkeene** [comment]
Hi! So sorry it took so long to get back to you. For whatever reason I was not notified of this issue. My apologies.

Anyways, I think I've already done what you're talking about. If you look at the example in example/example.go, you can see that can react on events. 

e..g:

```
	// Directory events
			if event.IsDirCreated() == true {
				log.Println("Directory created:", path.Clean(event.Path))
				if err := watcher.AddDescriptor(path.Clean(event.Path), 0); err != nil {
					panic(err)
				} else {
					log.Printf("Watch descriptor created and started for %s", event.Path)
				}
			}
			if event.IsDirRemoved() == true {
				log.Println("Directory removed:", path.Clean(event.Path))
				if err := watcher.RemoveDescriptor(path.Clean(event.Path)); err != nil {
					panic(err)
				} else {
					log.Printf("Watch descriptor removed for %s", event.Path)
				}
			}
```
Is this what you're thinking of? This would add watches for directories when they're created under the root, and delete them when removed.

Again, my apologies for the super late reply. I'm gonna go fix my notifications, and I will be sure to check back in case you, or anyone else has any questions.

**Comment by AxelWalsleben** [comment]
With AddDescriptor only the Watcher Event is not started .
My Solution is:
			if event.IsDirCreated() == true {
				log.Println("Directory created:", path.Clean(event.Path))
				watcher.AddDescriptor(path.Clean(event.Path), inotifyFlags)
				descriptor := watcher.GetDescriptorByPath(path.Clean(event.Path))
				descriptor.Start(watcher.FileDescriptor)

			}
After creating the Directory the Notify is directly started.

**Comment by tywkeene** [comment]
@AxelWalsleben is right, I should read my own code. 

Using `AddDescriptor()` the watch isn't started, you have to manually start it.

If I remember correctly (it's been a while), I did this because I was getting some really weird events that didn't seem to be valid when starting a lot of descriptors at once.
