### ISSUE TITLE
Build failing with go modules

### ISSUE THREAD

**Issue by markschmid** [tywkeene/go-fsevents#12]
When using go modules (go mod ...) building fails. I'm on macOS, cross-compiling for Linux.

```
go: finding github.com/tywkeene/go-fsevents v0.0.0-20190911221857-8a6f3576d56d
go build github.com/tywkeene/go-fsevents: build constraints exclude all Go files in /go/pkg/mod/github.com/tywkeene/go-fsevents@v0.0.0-20190911221857-8a6f3576d56d
```

I'm building for Docker, using:
```
RUN GOARCH=amd64 CGO_ENABLED=0 GOOS=linux go build -tags netgo -a -installsuffix 'static' -o /app .
```

Any ideas?

PS: It used to work fine and has only stopped since changing to Go Modules.

**Comment by markschmid** [comment]
Thanks, there is some progress made, specifically it now builds with Go Modules and ```CGO_ENABLED=1```.
The problem now is that my application binary won't start as it used to. Error message:

```
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

Prior versions of this library I was able to build using ```CGO_ENABLED=0``` which used to be much easier. I use an alpine container to build a single application binary and a ubuntu container onto which  copy the binary and (try to) run it.

**Comment by markschmid** [comment]
I have changed to a normal golang container for building (not alpine). Now it builds and runs. Please never mind and thanks again!

**Comment by tywkeene** [comment]
If I remember correctly, you can install libc6-compat in your alpine to get binaries built with `CGO_ENABLED=1` to run.

`RUN apk add --no-cache ca-certificates libc6-compat`

(`ca-certificates` is unnecessary for the binary to run, but it's recommended by the alpine folks)

Just thought I"d let you know if you still want to pursue that option, I don't blame you, alpine is tiny, makes deployments and uploads so much faster :)

Anyways, closing this comment for now. Feel free to open new issues if you run into anything else, I'll be more than glad to help.
