### ISSUE TITLE
WatcherOptions

### ISSUE THREAD

**Issue by markschmid** [tywkeene/go-fsevents#16]
Where did the fsevents.WatcherOptions go?

E.g. 
```
options := &fsevents.WatcherOptions{
  Recursive:       true,
  UseWatcherFlags: false,
}
```

Using those, the watcher was watching recursively also e.g. for file creation in subdirectories from the start. This does somehow not work anymore. Do we have to add every subdirectory to the watcher?

**Comment by markschmid** [comment]
Stupid me :)
https://github.com/tywkeene/go-fsevents/blob/2f255c0158ceb502b0e656b4bc9248458503e581/fsevents.go#L344

**Comment by markschmid** [comment]
Hmm, no... I really don't get it :(

How do I start a watcher that watches a directory with subdirectories as it used to be with  ```fsevents.WatcherOptions.Recursive``` ?

**Comment by markschmid** [comment]
I think the reason why it was not working for me was a misconfiguration of my handlers.
Now, after creating the watcher using ```NewWatcher()``` having an additional ```w.RecursiveAdd()``` seems to work fine.

**Comment by tywkeene** [comment]
Actually this highlights an issue I was pondering yesterday.

The `Watcher` object is basically just a list of watches, and it adds a descriptor for the "root" directory, but doesn't do it recursively and doesn't start the watch during the call to `NewWatcher`

I'm considering removing the initial watch descriptor from `NewWatcher`, so it removes the confusion on having to use either `AddDescriptor` or `RecursiveAdd`

Any comments/objections/concerns appreciated before I do this. Don't want to break everyone here.

**Comment by markschmid** [comment]
> I'm considering removing the initial watch descriptor from NewWatcher, so
> it removes the confusion on having to use either AddDescriptor or RecursiveAdd

I think that would help.

**Comment by tywkeene** [comment]
Just pushed https://github.com/tywkeene/go-fsevents/commit/7be7831a608d078f38a3cbba139d8d28b84e39fc to master. You should be able to get it working with minimal changes, and it should be much clearer and more understandable.

This should address the confusion when using `NewWatcher()` and expecting it to add/start a watch.

The new way it works is like this:

```
// NewWatcher doesn't accept any arguments anymore
w := NewWatcher()

// Add the descriptor to the watcher
d, err := w.AddDescriptor(dirPath)

// Start the descriptor
dir.Start()
```

Hope this helps. I'll leave this issue open if you have any more issues with this, otherwise go ahead and close it.

Cheers.

**Comment by markschmid** [comment]
Great, thanks a lot! It works as expected and to me it makes a lot of sense like this.

There are two things that I've noticed (already before this change) which I'm not sure about:
1) ```RecursiveAdd(rootDir)``` does not seem to add the ```rootDir``` to the watch (in the comment of the method, it says it does)
2) Even using a very simple setup with just a few watches (usind the "handlers" approeach), I'm getting a lot of ```handle not found: event mask: <mask>``` errors and I'm not sure what what's going wrong

In the coming days I might have time to look into this in more detail and put together a more clear scenario which is reproducible.

**Comment by tywkeene** [comment]
> 1. `RecursiveAdd(rootDir)` does not seem to add the `rootDir` to the watch (in the comment of the method, it says it does)

Yep, it's not getting added or started. Good catch.

I'll also go through and audit the documentation and make sure it all lines up and reflects the actual behavior.

> 2. Even using a very simple setup with just a few watches (usind the "handlers" approeach), I'm getting a lot of `handle not found: event mask: <mask>` errors and I'm not sure what what's going wrong

When you register a handle, you register it for a specific inotify event flags or flags OR'd together.
It's possible though that there's something wrong with the code that handles that, though. A reproducible snippet would be great.

I've actually looked at the code a bit, and realized that this approach is a bit brittle. So it may be worth a redesign.
